[project]
name = "velo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "typer[all]>=0.12.3",
    "rich>=13.7.1",
]

[project.optional-dependencies]
llm = [
    "dspy-ai>=2.4.3",
    "llama-cpp-python>=0.2.79",
]
